version: '3'

services:
  api:
    build: ./api
    ports: 
      - 3001:80
    volumes:
      - ./api:/app
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  client:
    build: ./client
    ports: 
      - 3000:3000
    volumes:
      - ./client:/client